### ISSUE TITLE
Separate record serialization from internal representation

### ISSUE THREAD

**Issue by mielvds** [pkiraly/metadata-qa-api#54]
At the moment, the input and output of the measure function are serialize strings (see for instance https://github.com/pkiraly/metadata-qa-api/blob/a01d7db2aca5f95eb68f1f503d24137406244c96/src/main/java/de/gwdg/metadataqa/api/calculator/CalculatorFacade.java#L322). 

Could it be made possible to also pass an internal (java) representation instead (simplest example would be an array)? This would simplify extensions such as reading from and writing to a RDBMS. Now, you would have to (de)serialize a record to a CSV string.

**Comment by pkiraly** [comment]
@mielvds 

I've created two additional functions:

* `List<String> measureAsList(String jsonRecord) throws InvalidJsonException`
* `Map<String, Object> measureAsMap(String jsonRecord) throws InvalidJsonException`

Please check if they do what you expected.

**Comment by mielvds** [comment]
@pkiraly thanks for this; it makes this already more flexible. However, it's more pressing on the input side. 

Something like `List<String> measureAsList(List<String> record) throws InvalidJsonException` 

Because of multiline columns, I use opencsv outside of this library to create individual records. With the current API for CSV, I have to serialize a the resulting`String[]` array back to CSV just to have it parsed again by your library. 

That said, this would cause problems for JSON, because it's not flat.  Maybe it's easier to simple implement CSV as a wrapper for JSON? Or us an internal data model to keep all serialization/deserialization out of the core components?

**Comment by pkiraly** [comment]
@mielvds 

I am aware of the problem. I haven't thought about the suggestion you made. I will implement it. Meantime, here is a solution based on opencsv:

```Java
CSVIterator iterator = new CSVIterator(new CSVReaderHeaderAware(new FileReader(file)));
while (iterator.hasNext()) {
  String line = CsvReader.toCsv(iterator.next());
  List<String> metrics = facade.measureAsList(String line);
  // save the metrics
}
```

**Comment by mielvds** [comment]
Ok, I've updated my repo. Works fine! I'm more or less ready to do a full blown completeness measurement.

**Comment by pkiraly** [comment]
@mielvds 

I've extended the API (CalculatorFacade) with some methods, so right now here is the full spectrum:

* String measure(String record) throws InvalidJsonException
* List<String> measureAsList(String record) throws InvalidJsonException
* List<Object> measureAsListOfObjects(String record) throws InvalidJsonException
* Map<String, Object> measureAsMap(String record) throws InvalidJsonException
* String measureCsv(List<String> record) throws InvalidJsonException
* List<String> measureCsvAsList(List<String> record) throws InvalidJsonException
* List<Object> measureCsvAsListOfObjects(List<String> record) throws InvalidJsonException
* Map<String, Object> measureCsvAsMap(List<String> record) throws InvalidJsonException

I choose List<String> and an input and did not implemented String[], because it is quite easy to convert them on the client side. Do you agree?

**Comment by mielvds** [comment]
Great work, thanks! Two minor questions:
- Can't you simply overload the `measureAsList` method with `measureCsvAsList(List<String> record)` or even `measureAsList(String[] record)`?
- I find converting from `String[]` to `List<String>` easier than the other way around, but that's indeed not a huge issue.

**Comment by pkiraly** [comment]
Hi @mielvds,

thanks for the feedback! I removed the ...Csv... from the method name, so right now you can use the same method name with `String` and `List<String>`:

* `String measure(String record) throws InvalidJsonException`
* `String measure(List<String> record) throws InvalidJsonException`
* `List<String> measureAsList(String record) throws InvalidJsonException`
* `List<String> measureAsList(List<String> record) throws InvalidJsonException`
* `List<Object> measureAsListOfObjects(String record) throws InvalidJsonException`
* `List<Object> measureAsListOfObjects(List<String> record) throws InvalidJsonException`
* `Map<String, Object> measureAsMap(String record) throws InvalidJsonException`
* `Map<String, Object> measureAsMap(List<String> record) throws InvalidJsonException`

I do not get your second question, as it was rather a statement, right?

**Comment by mielvds** [comment]
ha yes, sorry. The `.asArray(new String[0])` is more ugly than `new ArrayList(array)`, but that's java. I comletely support your choice for List.
