### ISSUE TITLE
JSON output not as expected

### ISSUE THREAD

**Issue by mielvds** [pkiraly/metadata-qa-api#80]
Hi @pkiraly !

The readme says the ouput json records of a basic completeness test should look like this

``` json
{
  "completeness":{
    "completeness":{
      "TOTAL":0.35294117647058826,
      "MANDATORY":1.0
    },
    "existence":{
      "url":true,
      "name":true,
      ...
    },
    "cardinality":{
      "url":1,
      "name":1,
      ...
    }
  }
}
```

(btw, why is the completeness key repeated? There's no need)

However, running `calculator.measureAsJson(record);` gives me something like

``` json
{
  "completeness":{
      "url":1,
      "name":1,
      ...
    }
  }
}
```

This doesn't seem right?

**Comment by pkiraly** [comment]
@mielvds 
1) the "completeness" class might measure 3 things: completeness, existence and cardinality. You can set if you want all the 3 or only one. But you are right, maybe we do not need this outer "completeness" in the output.

2) I will check it. It doesn't seem logical, or conform to the documentation. Could you provide the measurement configuration? (either here or via email)

Thanks!

**Comment by mielvds** [comment]
Will add a sample tomorrow. Btw, the CSV output comes out fine

**Comment by mielvds** [comment]
@pkiraly I'll close this, because when merging like we said in #83, the json output format can be revised
